name: "PR MiniBot (Python)"
description: "Runs python script on pull_request and can comment on PR"

inputs:
  github-token:
    description: "GitHub token to access API"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps (if any)
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f "${GITHUB_ACTION_PATH}/requirements.txt" ]; then
          pip install -r "${GITHUB_ACTION_PATH}/requirements.txt"
        fi

    - name: Run bot script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        python "${GITHUB_ACTION_PATH}/testing/py_script.py"
